export const characterClasses = [
	{
		classN: "Triggerman",
		weaponIndexes: [0, 5],
		pWeapon: "Machine Gun",
		sWeapon: "Grenade Launcher",
		folderName: "triggerman",
		hasDown: false,
	},
	{
		classN: "Detective",
		weaponIndexes: [1, 5],
		pWeapon: "Desert Eagle",
		sWeapon: "Grenade Launcher",
		folderName: "detective",
		hasDown: false,
	},
	{
		classN: "Hunter",
		weaponIndexes: [2, 7],
		pWeapon: "Sniper",
		sWeapon: "Machine Pistol",
		folderName: "hunter",
		hasDown: true,
	},
	{
		classN: "Run 'N Gun",
		weaponIndexes: [3],
		pWeapon: "Toy Blaster",
		sWeapon: "None",
		folderName: "billy",
		hasDown: false,
	},
	{
		classN: "Vince",
		weaponIndexes: [4, 5],
		pWeapon: "Shotgun",
		sWeapon: "Grenade Launcher",
		folderName: "vinc",
		hasDown: true,
	},
	{
		classN: "Rocketeer",
		name: "General Weiss",
		weaponIndexes: [6],
		pWeapon: "Rocket Launcher",
		sWeapon: "None",
		folderName: "rocketeer",
		hasDown: false,
	},
	{
		classN: "Spray N' Pray",
		weaponIndexes: [8],
		pWeapon: "Minigun",
		sWeapon: "None",
		folderName: "mbob",
		hasDown: true,
	},
	{
		classN: "Arsonist",
		weaponIndexes: [9],
		pWeapon: "Flamethrower",
		sWeapon: "None",
		folderName: "pyro",
		hasDown: true,
	},
	{
		classN: "Duck",
		weaponIndexes: [9],
		pWeapon: "Jump",
		sWeapon: "None",
		folderName: "boss2",
		hasDown: true,
	},
	{
		classN: "Nademan",
		weaponIndexes: [5],
		pWeapon: "Nade Launcher",
		sWeapon: "None",
		folderName: "demo",
		hasDown: false,
	},
];
export const specialClasses = [
	{
		pWeapon: "???",
		sWeapon: "???",
		folderName: "boss1",
		hasDown: false,
	},
	{
		pWeapon: "???",
		sWeapon: "???",
		folderName: "boss2",
		hasDown: false,
	},
];

export var weapons = [
	{
		name: "smg",
		weaponIndex: 0,
		dmg: 20,
		ammo: 24,
		maxAmmo: 24,
		reloadTime: 0,
		reloadSpeed: 800,
		fireRate: 143,
		spread: [0, 0, 0],
		spreadIndex: 0,
		width: 30,
		length: 90,
		yOffset: 55,
		holdDist: 5,

		bSpeed: 6,
		bWidth: 8,
		bHeight: 18,
		bRandScale: [0, 0],
		cAcc: 12,
		maxLife: 500,
		bulletsPerShot: 1,
		pierceCount: 1,
		bounce: false,
		distBased: false,
		explodeOnDeath: false,
		bDist: 48,
		bTrail: 2,
		bSprite: 0,
		glowWidth: 50,
		glowHeight: 100,
		shake: 0.4,
		lastShot: 0,
	},
	{ name: "revolver" },
	{ name: "sniper" },
	{ name: "toygun" },
	{ name: "shotgun" },
	{
		name: "grenades",
		weaponIndex: 5,
		dmg: 110,
		ammo: 1,
		maxAmmo: 1,
		reloadTime: 0,
		reloadSpeed: 7500,
		fireRate: 92,
		spread: [0, 0, 0],
		spreadIndex: 0,
		width: 30,
		length: 90,
		yOffset: 55,
		holdDist: 5,

		bSpeed: 2,
		bWidth: 24,
		bHeight: 24,
		bRandScale: [0, 0],
		cAcc: 12,
		maxLife: 800,
		bulletsPerShot: 1,
		pierceCount: 1,
		bounce: true,
		distBased: false,
		explodeOnDeath: true,
		bDist: 48,
		bTrail: 0,
		bSprite: 0,
		glowWidth: 50,
		glowHeight: 100,
		shake: 0.4,
		lastShot: 0,
	},
	{ name: "rockets" },
	{ name: "pistol" },
	{ name: "minigun" },
	{ name: "flamethrower" },
];

export const weaponNames = weapons.map((w) => [w.name]).flat();
